# .github/workflows/build.yml

name: Build and Deploy Lesson

on:
  workflow_dispatch:
    inputs:
      course:
        description: 'Course Name'
        required: true
      unit:
        description: 'Unit Name'
        required: true
      topic:
        description: 'Lesson Topic'
        required: true
      filePath:
        description: 'File Path for the new lesson'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log Received Data
        run: |
          echo "Workflow triggered via workflow_dispatch!"
          echo "Course: ${{ github.event.inputs.course }}"
          echo "Unit: ${{ github.event.inputs.unit }}"
          echo "Topic: ${{ github.event.inputs.topic }}"
          echo "File Path: ${{ github.event.inputs.filePath }}"

      - name: Generate Lesson Content with Gemini
        id: gemini
        run: |
          echo "--- Placeholder: Gemini API call will go here ---"
          echo "Topic: ${{ github.event.inputs.topic }}"
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Generate Quiz with Google Apps Script
        run: echo "TODO: Call Google Apps Script to generate quiz and get embed code."

      - name: Commit and Push New Lesson File
        run: echo "TODO: Commit the generated HTML file to ${{ github.event.inputs.filePath }} and push to main."
